#!/usr/bin/env bash
#
# Integration tests for real git operations
#
# Tests that hooks work correctly when triggered by actual git commands:
# - git commit
# - git checkout (branch switching)
# - git switch
# - git stash
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
TEST_DIR="$SCRIPT_DIR/test-gitops"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

TESTS_RUN=0
TESTS_FAILED=0

pass() {
    echo -e "${GREEN}[PASS]${NC} $*"
}

fail() {
    echo -e "${RED}[FAIL]${NC} $*"
    ((TESTS_FAILED++)) || true
}

info() {
    echo -e "${YELLOW}[TEST]${NC} $*"
    ((TESTS_RUN++)) || true
}

cleanup() {
    rm -rf "$TEST_DIR"
}

setup_repo() {
    cleanup
    mkdir -p "$TEST_DIR"
    cd "$TEST_DIR"

    # Initialize repo
    git init -q
    git config user.email "test@test.com"
    git config user.name "Test User"

    # Create initial files
    echo "# Original README" > README.md
    echo "# Original CLAUDE.md content" > CLAUDE.md
    echo "original_value: true" > config.yaml

    git add .
    git commit -q -m "Initial commit"

    # Install hooks directly (simulating install.sh --repo)
    mkdir -p .git/hooks
    cp "$PROJECT_DIR/hooks/local-override-lib.sh" .git/hooks/
    cp "$PROJECT_DIR/hooks/local-override-post-checkout" .git/hooks/post-checkout
    cp "$PROJECT_DIR/hooks/local-override-pre-commit" .git/hooks/pre-commit
    cp "$PROJECT_DIR/hooks/local-override-post-commit" .git/hooks/post-commit
    cp "$PROJECT_DIR/hooks/local-override-filter-smudge" .git/hooks/
    cp "$PROJECT_DIR/hooks/local-override-filter-clean" .git/hooks/
    chmod +x .git/hooks/*

    # Create config file
    cat > .local-overrides.yaml << 'EOF'
pattern: ".local"
files:
  - override: CLAUDE.local.md
    replaces:
      - CLAUDE.md
  - override: config.local.yaml
    replaces:
      - config.yaml
EOF

    git add .local-overrides.yaml
    git commit -q -m "Add local-overrides config"

    # Configure git filter driver using worktree-safe common git dir paths
    local common_git_dir
    common_git_dir=$(git rev-parse --git-common-dir)
    if [[ "$common_git_dir" != /* ]]; then
        common_git_dir="$TEST_DIR/$common_git_dir"
    fi

    git config --local filter.local-override.smudge "$common_git_dir/hooks/local-override-filter-smudge %f"
    git config --local filter.local-override.clean "$common_git_dir/hooks/local-override-filter-clean %f"
    git config --local filter.local-override.required false

    # Create .git/info/attributes for filter
    mkdir -p .git/info
    cat > .git/info/attributes << 'EOF'
# Auto-generated by git-local-override — do not edit manually
CLAUDE.md filter=local-override
config.yaml filter=local-override
EOF

    # Create local override files
    echo "# MY LOCAL CLAUDE.md - customized for my environment" > CLAUDE.local.md
    echo "local_value: true" > config.local.yaml

    # Apply overrides initially
    export PATH="$PROJECT_DIR/bin:$PATH"
    git-local-override apply 2>/dev/null || true
}

#------------------------------------------------------------------------------
# Tests
#------------------------------------------------------------------------------

test_commit_preserves_original() {
    info "Testing git commit preserves original content..."

    cd "$TEST_DIR"

    # Verify local content is in working tree
    if ! grep -q "MY LOCAL" CLAUDE.md; then
        fail "Pre-condition: local content not applied"
        return 1
    fi

    # Make a change to README (unrelated file)
    echo "# Updated README" > README.md
    git add README.md

    # Commit - pre-commit hook should restore original
    git commit -q -m "Update README"

    # Check what was actually committed for CLAUDE.md
    local committed_content
    committed_content=$(git show HEAD:CLAUDE.md)

    if echo "$committed_content" | grep -q "Original CLAUDE.md content"; then
        pass "Commit contains original content"
    else
        fail "Commit contains local content (should be original)"
        echo "Committed content: $committed_content"
        return 1
    fi
}

test_commit_restores_local_after() {
    info "Testing local content restored after commit..."

    cd "$TEST_DIR"

    # Make a change
    echo "Another change" >> README.md
    git add README.md
    git commit -q -m "Another update"

    # Check working tree has local content after commit
    if grep -q "MY LOCAL" CLAUDE.md; then
        pass "Local content restored after commit"
    else
        fail "Local content not restored after commit"
        cat CLAUDE.md
        return 1
    fi
}

test_commit_staged_override_file() {
    info "Testing commit with staged override file..."

    cd "$TEST_DIR"

    git update-index --no-skip-worktree CLAUDE.md

    echo "# TEMPORARY CHANGE - should be filtered" > CLAUDE.md
    git add CLAUDE.md

    if ! git commit -q -m "Commit CLAUDE.md" 2>/dev/null; then
        info "No changes to commit (clean filter returned original)"
        pass "Clean filter prevented staging different content"
        
        cp CLAUDE.local.md CLAUDE.md 2>/dev/null || true
        git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
        return 0
    fi

    local committed_content
    committed_content=$(git show HEAD:CLAUDE.md)

    if echo "$committed_content" | grep -q "Original CLAUDE.md content"; then
        pass "Clean filter ensured original content in commit"
    else
        fail "Clean filter failed - commit has wrong content"
        echo "Committed: $committed_content"
        return 1
    fi

    cp CLAUDE.local.md CLAUDE.md 2>/dev/null || true
    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true

    if grep -q "MY LOCAL" CLAUDE.md; then
        pass "Working tree restored to local content"
    else
        fail "Working tree not restored"
        return 1
    fi
}

test_branch_checkout_applies_overrides() {
    info "Testing branch checkout applies overrides..."

    cd "$TEST_DIR"

    # Get the default branch name
    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    # Create a new branch
    git checkout -q -b feature-branch

    # After checkout, local content should be applied
    if grep -q "MY LOCAL" CLAUDE.md; then
        pass "Override applied after branch creation"
    else
        fail "Override not applied after branch creation"
        return 1
    fi

    # Make a commit on this branch
    echo "Feature work" >> README.md
    git add README.md
    git commit -q -m "Feature commit"

    # Switch back to default branch
    git checkout -q "$default_branch"

    # Local content should still be there
    if grep -q "MY LOCAL" CLAUDE.md; then
        pass "Override applied after switching to $default_branch"
    else
        fail "Override not applied after switching to $default_branch"
        return 1
    fi
}

test_git_switch_applies_overrides() {
    info "Testing git switch applies overrides..."

    cd "$TEST_DIR"

    # Check if git switch is available (Git 2.23+)
    if ! git switch --help &>/dev/null; then
        info "git switch not available (Git < 2.23), skipping"
        pass "Skipped (git switch not available)"
        return 0
    fi

    # Get the default branch name
    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    # Create branch using switch
    git switch -q -c another-feature

    # Override should be applied
    if grep -q "MY LOCAL" CLAUDE.md; then
        pass "Override applied after git switch -c"
    else
        fail "Override not applied after git switch -c"
        return 1
    fi

    # Switch back to default branch
    git switch -q "$default_branch"

    if grep -q "MY LOCAL" CLAUDE.md; then
        pass "Override applied after git switch $default_branch"
    else
        fail "Override not applied after git switch $default_branch"
        return 1
    fi
}

test_multiple_files_override() {
    info "Testing multiple files are overridden..."

    cd "$TEST_DIR"

    # Check both files have local content
    if grep -q "MY LOCAL" CLAUDE.md && grep -q "local_value" config.yaml; then
        pass "Multiple files have local content"
    else
        fail "Not all files have local content"
        return 1
    fi

    # Commit something
    echo "test" >> README.md
    git add README.md
    git commit -q -m "Test commit"

    # Both should still have local content
    if grep -q "MY LOCAL" CLAUDE.md && grep -q "local_value" config.yaml; then
        pass "Multiple files preserved after commit"
    else
        fail "Some files lost local content after commit"
        return 1
    fi
}

test_no_override_without_local_file() {
    info "Testing file without .local version is unchanged..."

    cd "$TEST_DIR"

    # Remove the local file for config.yaml
    rm -f config.local.yaml

    # Clear skip-worktree before restore (git checkout doesn't work with skip-worktree)
    git update-index --no-skip-worktree config.yaml

    # Restore original
    git checkout HEAD -- config.yaml

    # Apply overrides
    git-local-override apply

    # config.yaml should have original content (no local file exists)
    if grep -q "original_value" config.yaml; then
        pass "File without local version has original content"
    else
        fail "File without local version was modified"
        return 1
    fi

    # CLAUDE.md should still have local content
    if grep -q "MY LOCAL" CLAUDE.md; then
        pass "Other files still have local content"
    else
        fail "Other files lost local content"
        return 1
    fi

    # Restore for other tests
    echo "local_value: true" > config.local.yaml
}

test_restore_command() {
    info "Testing restore command..."

    cd "$TEST_DIR"

    git-local-override restore

    local skip_worktree_cleared=true
    if git ls-files -v | grep -q "^S.*CLAUDE.md"; then
        skip_worktree_cleared=false
    fi

    if [[ "$skip_worktree_cleared" == true ]]; then
        pass "Restore cleared skip-worktree flags"
    else
        fail "Restore did not clear skip-worktree"
        return 1
    fi

    if grep -q "MY LOCAL" CLAUDE.md; then
        pass "With filters active, smudge applies local content (expected behavior)"
    else
        info "Checking if filters disabled..."
        if grep -q "Original CLAUDE.md content" CLAUDE.md; then
            pass "Original content visible (filters bypassed)"
        else
            fail "Unexpected content state"
            return 1
        fi
    fi

    git-local-override apply
}

test_dirty_working_tree_commit() {
    info "Testing commit with dirty working tree..."

    cd "$TEST_DIR"

    echo "Unstaged change" >> README.md

    git update-index --no-skip-worktree config.yaml

    echo "temp_value: false" > config.yaml
    git add config.yaml

    if git diff --cached --quiet; then
        info "Clean filter returned original (matches HEAD)"
        pass "Clean filter working correctly with dirty tree"
        git checkout HEAD -- README.md
        cp config.local.yaml config.yaml 2>/dev/null || true
        git update-index --skip-worktree config.yaml 2>/dev/null || true
        return 0
    fi

    if ! git commit -q -m "Commit config" 2>/dev/null; then
        fail "Commit failed"
        git checkout HEAD -- README.md
        return 1
    fi

    local committed_content
    committed_content=$(git show HEAD:config.yaml)

    if echo "$committed_content" | grep -q "original_value"; then
        pass "Config committed with original content (clean filter)"
    else
        fail "Config committed with wrong content"
        git checkout HEAD -- README.md
        return 1
    fi

    cp config.local.yaml config.yaml 2>/dev/null || true
    git update-index --skip-worktree config.yaml 2>/dev/null || true

    if grep -q "local_value" config.yaml; then
        pass "Local content restored in working tree"
    else
        fail "Local content not restored"
        git checkout HEAD -- README.md
        return 1
    fi

    if grep -q "Unstaged change" README.md; then
        pass "Unstaged changes preserved"
    else
        fail "Unstaged changes lost"
        git checkout HEAD -- README.md
        return 1
    fi

    git checkout HEAD -- README.md
}

test_hooks_skip_without_config() {
    info "Testing hooks skip without config file..."

    cd "$TEST_DIR"

    # Remove config
    rm -f .local-overrides.yaml .local-overrides

    # Clear skip-worktree before checkout (git checkout doesn't work with skip-worktree)
    git update-index --no-skip-worktree CLAUDE.md 2>/dev/null || true
    git update-index --no-skip-worktree config.yaml 2>/dev/null || true

    # Restore original content deterministically (bypass smudge filter)
    git show "HEAD:CLAUDE.md" > CLAUDE.md
    git show "HEAD:config.yaml" > config.yaml

    # Make a change and commit
    echo "No config test" >> README.md
    git add README.md
    git commit -q -m "No config commit"

    # Files should still have original content (not local)
    if grep -q "Original CLAUDE.md content" CLAUDE.md; then
        pass "Hooks gracefully handle missing config"
    else
        fail "Hooks modified files without config"
        return 1
    fi

    # Restore config
    cat > .local-overrides.yaml << 'EOF'
pattern: ".local"
files:
  - override: CLAUDE.local.md
    replaces:
      - CLAUDE.md
  - override: config.local.yaml
    replaces:
      - config.yaml
EOF
    git-local-override apply 2>/dev/null || true
}

#------------------------------------------------------------------------------
# Filter Integration Tests
#------------------------------------------------------------------------------

test_checkout_with_divergent_overridden_file() {
    info "Testing checkout with divergent branches (PRIMARY BUG FIX)..."

    cd "$TEST_DIR"

    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    if git show-ref --verify --quiet "refs/heads/feature-diverge"; then
        git branch -D feature-diverge 2>/dev/null || true
    fi

    git checkout -q -b feature-diverge

    echo "# Feature branch README change" >> README.md
    git add README.md
    git commit -q -m "Change on feature branch"

    git checkout -q "$default_branch"

    if [[ ! -f "CLAUDE.local.md" ]]; then
        echo "# MY LOCAL CLAUDE.md - personal instructions" > CLAUDE.local.md
    fi

    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
    cp CLAUDE.local.md CLAUDE.md

    local checkout_output
    checkout_output=$(git checkout feature-diverge 2>&1)
    local checkout_status=$?

    if [[ $checkout_status -ne 0 ]]; then
        fail "Checkout failed: $checkout_output"
        git checkout -q "$default_branch" 2>/dev/null || true
        return 1
    fi

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md; then
        pass "Checkout succeeded and local override preserved"
    else
        fail "Checkout succeeded but local override lost"
        git checkout -q "$default_branch"
        return 1
    fi

    local status_output
    status_output=$(git status --porcelain | grep -v "^??" || true)
    
    if [[ -z "$status_output" ]]; then
        pass "Git status is clean after checkout (ignoring untracked files)"
    else
        fail "Git status shows changes: $status_output"
        git checkout -q "$default_branch"
        return 1
    fi

    git checkout -q "$default_branch"
}

test_switch_with_divergent_overridden_file() {
    info "Testing git switch with divergent branches..."

    if ! git switch --help &>/dev/null; then
        info "git switch not available (Git < 2.23), skipping"
        pass "Skipped (git switch not available)"
        return 0
    fi

    cd "$TEST_DIR"

    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    if ! git show-ref --verify --quiet "refs/heads/feature-switch-test"; then
        git checkout -q -b feature-switch-test
        echo "# Feature for switch test" >> README.md
        git add README.md
        git commit -q -m "Feature commit for switch test"
        git checkout -q "$default_branch"
    fi

    if [[ ! -f "CLAUDE.local.md" ]]; then
        echo "# MY LOCAL CLAUDE.md - personal instructions" > CLAUDE.local.md
    fi

    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
    cp CLAUDE.local.md CLAUDE.md

    if ! git switch -q feature-switch-test 2>/dev/null; then
        fail "git switch failed"
        git checkout -q "$default_branch"
        return 1
    fi

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md; then
        pass "git switch preserved local override"
    else
        fail "git switch lost local override"
        git checkout -q "$default_branch"
        return 1
    fi

    local status_output
    status_output=$(git status --porcelain | grep -v "^??" || true)
    
    if [[ -z "$status_output" ]]; then
        pass "Git status is clean after switch"
    else
        fail "Git status shows changes after switch"
        git checkout -q "$default_branch"
        return 1
    fi

    git switch -q "$default_branch" || git checkout -q "$default_branch"
}

test_pull_with_overridden_file() {
    info "Testing git pull with overridden file..."

    cd "$TEST_DIR"

    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    if git show-ref --verify --quiet "refs/heads/feature-pull"; then
        git branch -D feature-pull 2>/dev/null || true
    fi

    git checkout -q -b feature-pull
    echo "# Feature pull change" >> README.md
    git add README.md
    git commit -q -m "Remote-like change"
    git checkout -q "$default_branch"

    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
    cp CLAUDE.local.md CLAUDE.md

    if ! git merge -q --no-edit feature-pull 2>/dev/null; then
        fail "Merge (simulating pull) failed"
        git merge --abort 2>/dev/null || true
        return 1
    fi

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md; then
        pass "Local override preserved after merge (simulating pull)"
    else
        fail "Local override lost after merge"
        return 1
    fi

    local status_output
    status_output=$(git status --porcelain | grep -v "^??" || true)
    
    if [[ -z "$status_output" ]]; then
        pass "Git status is clean after merge"
    else
        fail "Git status shows changes"
        return 1
    fi
}

test_merge_with_overridden_file() {
    info "Testing git merge with overridden file..."

    cd "$TEST_DIR"

    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    if git show-ref --verify --quiet "refs/heads/merge-test-branch"; then
        git branch -D merge-test-branch 2>/dev/null || true
    fi
    
    git checkout -q -b merge-test-branch
    echo "# Merge branch change" >> README.md
    git add README.md
    git commit -q -m "Change on merge branch"
    git checkout -q "$default_branch"

    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
    cp CLAUDE.local.md CLAUDE.md

    if ! git merge -q --no-edit merge-test-branch 2>/dev/null; then
        fail "git merge failed"
        git merge --abort 2>/dev/null || true
        return 1
    fi

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md; then
        pass "Local override preserved after merge"
    else
        fail "Local override lost after merge"
        return 1
    fi

    local status_output
    status_output=$(git status --porcelain | grep -v "^??" || true)
    
    if [[ -z "$status_output" ]]; then
        pass "Git status is clean after merge"
    else
        fail "Git status shows changes"
        return 1
    fi
}

test_rebase_with_overridden_file() {
    info "Testing git rebase with overridden file..."

    cd "$TEST_DIR"

    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    if git show-ref --verify --quiet "refs/heads/rebase-test-branch"; then
        git branch -D rebase-test-branch 2>/dev/null || true
    fi

    git checkout -q -b rebase-test-branch HEAD~1 2>/dev/null || git checkout -q -b rebase-test-branch
    echo "New file for rebase" > rebase-file.txt
    git add rebase-file.txt
    git commit -q -m "Commit for rebase"

    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
    cp CLAUDE.local.md CLAUDE.md

    if ! git rebase -q "$default_branch" 2>/dev/null; then
        info "Rebase had conflicts or issues, aborting"
        git rebase --abort 2>/dev/null || true
        git checkout -q "$default_branch"
        pass "Rebase test skipped (conflicts)"
        return 0
    fi

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md; then
        pass "Local override preserved after rebase"
    else
        fail "Local override lost after rebase"
        git checkout -q "$default_branch"
        return 1
    fi

    local status_output
    status_output=$(git status --porcelain | grep -v "^??" || true)
    
    if [[ -z "$status_output" ]]; then
        pass "Git status is clean after rebase"
    else
        info "Status: $status_output"
        pass "Rebase completed (status may show rebase artifacts)"
    fi

    git checkout -q "$default_branch"
}

test_stash_with_overridden_file() {
    info "Testing git stash with overridden file..."

    cd "$TEST_DIR"

    echo "# Temporary change" >> README.md
    git add README.md

    if ! git stash -q 2>/dev/null; then
        fail "git stash failed"
        git reset HEAD README.md 2>/dev/null || true
        return 1
    fi

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md; then
        pass "Local override preserved after stash"
    else
        fail "Local override lost after stash"
        return 1
    fi

    if ! git stash pop -q 2>/dev/null; then
        fail "git stash pop failed"
        git stash drop 2>/dev/null || true
        return 1
    fi

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md; then
        pass "Local override preserved after stash pop"
    else
        fail "Local override lost after stash pop"
        return 1
    fi

    git checkout HEAD -- README.md 2>/dev/null || true
}

test_commit_still_contains_original() {
    info "Testing commit contains original content with filters active..."

    cd "$TEST_DIR"

    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
    cp CLAUDE.local.md CLAUDE.md

    echo "Test change for commit test" >> README.md
    git add README.md
    git commit -q -m "Test commit with filters"

    local committed_claude
    committed_claude=$(git show HEAD:CLAUDE.md 2>/dev/null || echo "")

    if echo "$committed_claude" | grep -q "Original CLAUDE.md content"; then
        pass "Committed content is original (not local override)"
    else
        fail "Committed content contains local override"
        echo "Committed: $committed_claude"
        return 1
    fi
}

test_filter_and_hooks_coexist() {
    info "Testing filters and hooks work together..."

    cd "$TEST_DIR"

    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
    git update-index --skip-worktree config.yaml 2>/dev/null || true

    cp CLAUDE.local.md CLAUDE.md 2>/dev/null || true
    cp config.local.yaml config.yaml 2>/dev/null || true

    echo "Change for coexist test" >> README.md
    git add README.md
    git commit -q -m "Test coexistence"

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md && grep -q "local_value" config.yaml; then
        pass "Both hooks and filters applied local content after commit"
    else
        fail "Hooks or filters did not apply correctly"
        return 1
    fi

    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    if git show-ref --verify --quiet "refs/heads/coexist-test-branch"; then
        git branch -D coexist-test-branch 2>/dev/null || true
    fi
    
    git checkout -q -b coexist-test-branch
    git checkout -q "$default_branch"

    if grep -q "MY LOCAL CLAUDE.md" CLAUDE.md && grep -q "local_value" config.yaml; then
        pass "Filters and hooks coexist on checkout"
    else
        fail "Filters or hooks failed on checkout"
        return 1
    fi
}

test_no_override_file_normal_checkout() {
    info "Testing checkout without .local file works normally..."

    cd "$TEST_DIR"

    rm -f config.local.yaml

    git update-index --no-skip-worktree config.yaml 2>/dev/null || true
    git checkout HEAD -- config.yaml

    local default_branch
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    if ! git show-ref --verify --quiet "refs/heads/passthrough-test-branch"; then
        git checkout -q -b passthrough-test-branch
        git checkout -q "$default_branch"
    else
        git checkout -q passthrough-test-branch
        git checkout -q "$default_branch"
    fi

    if grep -q "original_value" config.yaml; then
        pass "File without .local override passes through normally"
    else
        fail "File without .local override was modified"
        return 1
    fi

    echo "local_value: true" > config.local.yaml
}

test_disable_env_var_allows_restore() {
    info "Testing GIT_LOCAL_OVERRIDE_DISABLE=1 restores original..."

    cd "$TEST_DIR"

    if ! grep -q "MY LOCAL CLAUDE.md" CLAUDE.md; then
        cp CLAUDE.local.md CLAUDE.md 2>/dev/null || true
    fi

    git update-index --no-skip-worktree CLAUDE.md 2>/dev/null || true

    GIT_LOCAL_OVERRIDE_DISABLE=1 git checkout HEAD -- CLAUDE.md

    if grep -q "Original CLAUDE.md content" CLAUDE.md; then
        pass "GIT_LOCAL_OVERRIDE_DISABLE=1 restored true original"
    else
        fail "GIT_LOCAL_OVERRIDE_DISABLE=1 did not restore original"
        cat CLAUDE.md
        return 1
    fi

    cp CLAUDE.local.md CLAUDE.md 2>/dev/null || true
    git update-index --skip-worktree CLAUDE.md 2>/dev/null || true
}

test_worktree_add_with_filters() {
    info "Testing git worktree add works with filters..."

    cd "$TEST_DIR"

    local default_branch
    local worktree_branch="worktree-filter-test-branch"
    local worktree_dir="$TEST_DIR/worktrees/worktree-filter-test"
    default_branch=$(git rev-parse --abbrev-ref HEAD)

    rm -rf "$worktree_dir"
    mkdir -p "$TEST_DIR/worktrees"
    git branch -D "$worktree_branch" 2>/dev/null || true

    local output
    output=$(git worktree add -b "$worktree_branch" "$worktree_dir" "$default_branch" 2>&1)
    local status=$?

    if [[ $status -ne 0 ]]; then
        fail "git worktree add failed: $output"
        git worktree remove -f "$worktree_dir" 2>/dev/null || true
        git branch -D "$worktree_branch" 2>/dev/null || true
        return 1
    fi

    if [[ -d "$worktree_dir" ]]; then
        pass "git worktree add succeeded with filters configured"
    else
        fail "Worktree directory was not created"
        git branch -D "$worktree_branch" 2>/dev/null || true
        return 1
    fi

    git worktree remove -f "$worktree_dir" 2>/dev/null || true
    git branch -D "$worktree_branch" 2>/dev/null || true
}

#------------------------------------------------------------------------------
# Main
#------------------------------------------------------------------------------

main() {
    echo ""
    echo "========================================"
    echo "  Git Operations Integration Tests"
    echo "========================================"
    echo ""

    # Add project bin to PATH
    export PATH="$PROJECT_DIR/bin:$PATH"

    setup_repo

    test_commit_preserves_original
    test_commit_restores_local_after
    test_commit_staged_override_file
    test_branch_checkout_applies_overrides
    test_git_switch_applies_overrides
    test_multiple_files_override
    test_no_override_without_local_file
    test_restore_command
    test_dirty_working_tree_commit
    test_hooks_skip_without_config
    test_checkout_with_divergent_overridden_file
    test_switch_with_divergent_overridden_file
    test_pull_with_overridden_file
    test_merge_with_overridden_file
    test_rebase_with_overridden_file
    test_stash_with_overridden_file
    test_commit_still_contains_original
    test_filter_and_hooks_coexist
    test_no_override_file_normal_checkout
    test_disable_env_var_allows_restore
    test_worktree_add_with_filters

    cleanup

    echo ""
    echo "========================================"
    if [[ $TESTS_FAILED -eq 0 ]]; then
        echo -e "  ${GREEN}All $TESTS_RUN tests passed!${NC}"
        exit 0
    else
        echo -e "  ${RED}$TESTS_FAILED/$TESTS_RUN tests failed${NC}"
        exit 1
    fi
    echo "========================================"
}

main "$@"
