#!/usr/bin/env bash
#
# local-override-lib.sh
#
# Shared library for git-local-override hooks.
# This file is sourced by the hook scripts.
#

HOOK_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_LIB_DIR="$(cd "$HOOK_LIB_DIR/.." 2>/dev/null && pwd || true)"
SHARED_RESOLVER_PATH=""

if [[ -f "$HOOK_LIB_DIR/local-override-resolver.sh" ]]; then
    SHARED_RESOLVER_PATH="$HOOK_LIB_DIR/local-override-resolver.sh"
elif [[ -n "$REPO_LIB_DIR" && -f "$REPO_LIB_DIR/shared/local-override-resolver.sh" ]]; then
    SHARED_RESOLVER_PATH="$REPO_LIB_DIR/shared/local-override-resolver.sh"
else
    echo "Error: local-override-resolver.sh not found" >&2
    return 1 2>/dev/null || exit 1
fi

# shellcheck source=local-override-resolver.sh
source "$SHARED_RESOLVER_PATH"

local_override_log() {
    printf 'git-local-override: %s\n' "$*" >&2
}

local_override_trace_log() {
    if local_override_trace_enabled; then
        printf 'Trace[%s]: %s\n' "${1:-hook}" "${2:-}" >&2
    fi
}

run_with_lifecycle_logging() {
    local operation_name="$1"
    shift

    local exit_code=0

    local_override_log "$operation_name started"
    "$@"
    exit_code=$?

    if [[ "$exit_code" -eq 0 ]]; then
        local_override_log "$operation_name finished"
        return 0
    fi

    local_override_log "$operation_name failed (exit $exit_code)"
    return "$exit_code"
}

run_with_trace_logging() {
    local operation_name="$1"
    shift

    if local_override_trace_enabled; then
        run_with_lifecycle_logging "$operation_name" "$@"
        return $?
    fi

    "$@"
}

read_managed_targets_from_attributes() {
    local repo_root="$1"
    local attributes_file=""
    local seen_targets=""
    local line=""
    local target=""

    attributes_file="$(get_attributes_file_path "$repo_root" 2>/dev/null || true)"
    [[ -n "$attributes_file" && -f "$attributes_file" ]] || return 1

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -n "$line" ]] || continue
        [[ "$line" == \#* ]] && continue
        [[ "$line" == *"filter=local-override"* ]] || continue

        target="${line%% filter=local-override*}"
        [[ -n "$target" ]] || return 1

        if [[ $'\n'"$seen_targets"$'\n' == *$'\n'"$target"$'\n'* ]]; then
            continue
        fi

        printf '%s\n' "$target"
        seen_targets="$seen_targets
$target"
    done < "$attributes_file"
}

read_config_entries_from_attributes() {
    local repo_root="$1"
    local seen_entries=""
    local target=""
    local override=""
    local entry=""

    while IFS= read -r target || [[ -n "$target" ]]; do
        [[ -n "$target" ]] || continue

        override="$(get_override_for_target "$target" "$repo_root" 2>/dev/null || true)"
        [[ -n "$override" ]] || return 1

        entry="$target|$override"
        if [[ $'\n'"$seen_entries"$'\n' == *$'\n'"$entry"$'\n'* ]]; then
            continue
        fi

        printf '%s\n' "$entry"
        seen_entries="$seen_entries
$entry"
    done < <(read_managed_targets_from_attributes "$repo_root")
}

sync_attributes_entries() {
    local repo_root="$1"
    local config_entries="${2:-}"
    local attributes_file=""
    local temp_file=""
    local line=""
    local seen_targets=""
    local entry=""
    local target=""
    local has_targets=false

    attributes_file="$(get_attributes_file_path "$repo_root")" || return 1
    temp_file="$(mktemp)"

    mkdir -p "$(dirname "$attributes_file")"

    if [[ -f "$attributes_file" ]]; then
        while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ "$line" == *"filter=local-override"* ]]; then
                continue
            fi
            if [[ "$line" == *"Auto-generated by git-local-override"* ]]; then
                continue
            fi
            printf '%s\n' "$line" >> "$temp_file"
        done < "$attributes_file"
    fi

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        [[ -n "$entry" ]] || continue

        target="${entry%%|*}"
        [[ -n "$target" ]] || continue

        if [[ $'\n'"$seen_targets"$'\n' == *$'\n'"$target"$'\n'* ]]; then
            continue
        fi

        seen_targets="$seen_targets
$target"
        has_targets=true
    done <<< "$config_entries"

    if [[ "$has_targets" == true ]]; then
        if [[ -s "$temp_file" ]]; then
            printf '\n' >> "$temp_file"
        fi

        printf '%s\n' '# Auto-generated by git-local-override — do not edit manually' >> "$temp_file"

        while IFS= read -r target || [[ -n "$target" ]]; do
            [[ -n "$target" ]] || continue
            printf '%s filter=local-override\n' "$target" >> "$temp_file"
        done <<< "$seen_targets"
    fi

    mv "$temp_file" "$attributes_file"
}

# Keyed to the per-worktree git dir so different checkouts of the same repo
# don't share transient commit state.
get_post_commit_state_file() {
    local repo_root="$1"
    local worktree_git_dir=""

    worktree_git_dir="$(git -C "$repo_root" rev-parse --absolute-git-dir 2>/dev/null || echo "")"
    [[ -n "$worktree_git_dir" ]] || return 1

    printf '%s\n' "$worktree_git_dir/local-override-post-commit-state"
}

clear_post_commit_state() {
    local repo_root="$1"
    local state_file=""

    state_file="$(get_post_commit_state_file "$repo_root" 2>/dev/null || true)"
    [[ -n "$state_file" ]] || return 0

    rm -f "$state_file"
}

# Re-apply overrides recorded by pre-commit, if a state file is present, then
# clear it. Safe to call when no state file exists (no-op). Used by both
# post-commit (on commit success) and post-checkout (to heal an aborted commit
# that left originals in the working tree and the state file behind).
reapply_post_commit_state() {
    local repo_root="$1"
    local state_file=""
    local entry target override
    state_file="$(get_post_commit_state_file "$repo_root" 2>/dev/null || true)"
    [[ -n "$state_file" && -f "$state_file" ]] || return 0

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        [[ -z "$entry" ]] && continue

        # Parse entry: "target|override" (override may be absolute — anchored
        # at the resolution root by pre-commit)
        target="${entry%%|*}"
        override="${entry#*|}"
        [[ "$override" == /* ]] || override="$repo_root/$override"

        if [[ -f "$override" && -f "$repo_root/$target" ]]; then
            # $override is absolute (anchored at the resolution root by
            # pre-commit); guard it via its own parent so the symlink gate
            # still applies to the absolute path.
            if ! path_is_symlink_safe "$repo_root" "$target" \
               || ! path_is_symlink_safe "$(dirname "$override")" "$(basename "$override")"; then
                printf 'git-local-override: refusing symlinked path for %s\n' "$target" >&2
                continue
            fi
            cp "$override" "$repo_root/$target"
        fi
    done < "$state_file"

    rm -f "$state_file"
}

# Keyed to the per-worktree git dir (like the post-commit state file) so
# linked worktrees don't share a stale stamp.
get_config_stamp_file() {
    local repo_root="$1"
    local worktree_git_dir=""

    worktree_git_dir="$(git -C "$repo_root" rev-parse --absolute-git-dir 2>/dev/null || echo "")"
    [[ -n "$worktree_git_dir" ]] || return 1

    printf '%s\n' "$worktree_git_dir/local-override-config-stamp"
}

# Content stamp of the discovered config set: one "path|cksum size" line per
# discovered config file. Captures adds/removes/edits of gitignored or
# untracked configs, which a tracked HEAD diff cannot see. Content-based
# (cksum) rather than mtime-based: `stat` flags differ between BSD and GNU,
# mtime only has one-second granularity, and config files are small enough
# that reading them is negligible next to the discovery walk itself.
compute_config_stamp() {
    local resolution_root="$1"
    local config_path=""
    local checksum=""

    while IFS= read -r config_path || [[ -n "$config_path" ]]; do
        [[ -n "$config_path" ]] || continue
        checksum="$(cksum < "$resolution_root/$config_path" 2>/dev/null || printf 'unreadable\n')"
        printf '%s|%s\n' "$config_path" "$checksum"
    done < <(get_cached_config_files "$resolution_root")
}

# Record the config stamp after a successful full (slow-path) resolution,
# which is the authority for what the synced attributes were built from.
write_config_stamp() {
    local repo_root="$1"
    local resolution_root="$2"
    local stamp_file=""

    stamp_file="$(get_config_stamp_file "$repo_root" 2>/dev/null || true)"
    [[ -n "$stamp_file" ]] || return 0

    compute_config_stamp "$resolution_root" > "$stamp_file"
}

# Succeeds only when a recorded stamp exists and matches the current on-disk
# config set. A missing stamp (fresh install, first checkout) fails the match
# so callers fall back to the full slow path, which records it.
config_stamp_matches() {
    local repo_root="$1"
    local resolution_root="$2"
    local stamp_file=""
    local stored_stamp=""
    local current_stamp=""

    stamp_file="$(get_config_stamp_file "$repo_root" 2>/dev/null || true)"
    [[ -n "$stamp_file" && -f "$stamp_file" ]] || return 1

    stored_stamp="$(cat "$stamp_file" 2>/dev/null || true)"
    current_stamp="$(compute_config_stamp "$resolution_root")"

    [[ "$stored_stamp" == "$current_stamp" ]]
}

clear_legacy_skip_worktree() {
    local repo_root="$1"
    local config_entries="${2:-}"
    local repaired_count=0
    local seen_targets=""
    local entry=""
    local target=""
    local ls_output=""

    if [[ -z "$config_entries" ]]; then
        config_entries="$(read_config "$repo_root")"
    fi

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        [[ -z "$entry" ]] && continue

        target="${entry%%|*}"
        [[ -n "$target" ]] || continue

        if [[ $'\n'"$seen_targets"$'\n' == *$'\n'"$target"$'\n'* ]]; then
            continue
        fi
        seen_targets="$seen_targets
$target"

        if ! git -C "$repo_root" ls-files --error-unmatch -- "$target" >/dev/null 2>&1; then
            continue
        fi

        ls_output="$(git -C "$repo_root" ls-files -v -- "$target" 2>/dev/null || true)"
        if [[ "${ls_output:0:1}" != "S" ]]; then
            continue
        fi

        git -C "$repo_root" update-index --no-skip-worktree -- "$target"
        ((repaired_count++)) || true
    done <<< "$config_entries"

    printf '%s\n' "$repaired_count"
}

# Per-worktree marker recording that the one-time legacy skip-worktree repair has
# already run. skip-worktree is per-worktree index state, so the marker is keyed
# to the per-worktree absolute git dir (like get_post_commit_state_file), not the
# shared common dir — each worktree migrates its own index once.
skip_worktree_repair_marker() {
    local repo_root="$1"
    local worktree_git_dir=""

    worktree_git_dir="$(git -C "$repo_root" rev-parse --absolute-git-dir 2>/dev/null || echo "")"
    [[ -n "$worktree_git_dir" ]] || return 1

    printf '%s\n' "$worktree_git_dir/local-override-skipworktree-repaired"
}

# One-shot gated form of clear_legacy_skip_worktree for the hot paths
# (post-checkout, pre-commit, pre-rebase). Once the per-worktree marker exists the
# repair is skipped, so the two git subprocesses per managed target are only paid
# once per worktree instead of on every checkout/commit. install/sync-filters call
# the ungated clear_legacy_skip_worktree directly and remain the escape hatch for
# stray legacy bits. Prints the repaired count (0 when short-circuited) to match
# the count contract callers expect.
clear_legacy_skip_worktree_once() {
    local repo_root="$1"
    local config_entries="${2:-}"
    local marker=""
    local repaired=""

    marker="$(skip_worktree_repair_marker "$repo_root" 2>/dev/null || true)"
    if [[ -n "$marker" && -f "$marker" ]]; then
        printf '0\n'
        return 0
    fi

    repaired="$(clear_legacy_skip_worktree "$repo_root" "$config_entries")"
    [[ -n "$marker" ]] && : > "$marker"
    printf '%s\n' "$repaired"
}
