#!/usr/bin/env bash
#
# local-override-resolver.sh
#
# Shared recursive config resolver for git-local-override.
#

CONFIG_FILE_NAME=".local-overrides.yaml"

# Sentinel emitted (as the target field) by read_config_entries_for_file when
# a config entry fails path normalization. Consumers read the parser through
# process substitution, so its exit status is invisible to them — the sentinel
# is how the failure stays visible. validate_config fails on it (the gate);
# other consumers skip it. Must never collide with a real repo-relative path.
LOCAL_OVERRIDE_PARSE_ERROR_SENTINEL="__LOCAL_OVERRIDE_PARSE_ERROR__"

# Cache for discover_config_files results (temp file path, empty = no cache)
_DISCOVER_CACHE_FILE=""
_DISCOVER_CACHE_ROOT=""

local_override_trace_enabled() {
    [[ "${GIT_LOCAL_OVERRIDE_TRACE:-0}" == "1" ]]
}

# Tag-aware trace log (single canonical implementation; lib.sh no longer
# shadows it). A single argument prints untagged `Trace: <msg>`; two or more
# arguments print `Trace[<tag>]: <msg...>` (the first arg is the tag). This
# keeps every existing call site's format: 1-arg resolver calls stay untagged,
# and 2-arg calls (clean core, hook code) stay tagged regardless of entry point.
local_override_trace_log() {
    if local_override_trace_enabled; then
        if [[ $# -ge 2 ]]; then
            local trace_tag="$1"
            shift
            printf 'Trace[%s]: %s\n' "$trace_tag" "$*" >&2
        else
            printf 'Trace: %s\n' "${1:-}" >&2
        fi
    fi
}

resolver_now_milliseconds() {
    if command -v perl >/dev/null 2>&1; then
        perl -MTime::HiRes=time -e 'printf("%.0f\n", time() * 1000)'
        return 0
    fi

    printf '%s000\n' "$(date +%s)"
}

resolver_elapsed_milliseconds() {
    local start_ms="$1"
    local end_ms

    end_ms="$(resolver_now_milliseconds)"
    printf '%s\n' "$((end_ms - start_ms))"
}

count_list_entries() {
    local input="${1:-}"
    local line=""
    local count=0

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -n "$line" ]] || continue
        ((count++)) || true
    done <<< "$input"

    printf '%s\n' "$count"
}

# Git-dir/path helpers. These use the return-non-zero contract (never die):
# the resolver is sourced by hooks that must not hard-exit. Callers that want
# fatal behavior (the CLI) die at the call site.
get_repo_root() {
    git rev-parse --show-toplevel 2>/dev/null
}

# Git common directory as an absolute path (shared across linked worktrees).
get_common_git_dir() {
    local repo_root="$1"
    local common_git_dir=""

    common_git_dir="$(git -C "$repo_root" rev-parse --git-common-dir 2>/dev/null || echo "")"
    [[ -n "$common_git_dir" ]] || return 1

    if [[ "$common_git_dir" != /* ]]; then
        common_git_dir="$repo_root/$common_git_dir"
    fi

    printf '%s\n' "$common_git_dir"
}

get_attributes_file_path() {
    local repo_root="$1"
    local attributes_path=""

    attributes_path="$(git -C "$repo_root" rev-parse --git-path info/attributes 2>/dev/null || echo "")"
    [[ -n "$attributes_path" ]] || return 1

    if [[ "$attributes_path" != /* ]]; then
        attributes_path="$repo_root/$attributes_path"
    fi

    printf '%s\n' "$attributes_path"
}

# Canonical attributes-rewrite core. Preserves foreign lines in
# .git/info/attributes, drops the managed `filter=local-override` block, and
# regenerates it from the given `target|override` config entries (deduped).
# Return-non-zero contract (resolver never dies); the CLI dies at its call site.
# This is the single implementation the hook (lib.sh), the CLI, and the
# installer all delegate to (precedent: run_local_override_smudge/clean).
sync_attributes_entries() {
    local repo_root="$1"
    local config_entries="${2:-}"
    local attributes_file=""
    local temp_file=""
    local line=""
    local seen_targets=""
    local entry=""
    local target=""
    local has_targets=false
    local trace_on=false
    local total_start_ms=0
    local preserved_line_count=0
    local managed_target_count=0

    if local_override_trace_enabled; then
        trace_on=true
        total_start_ms="$(resolver_now_milliseconds)"
    fi

    attributes_file="$(get_attributes_file_path "$repo_root")" || return 1
    temp_file="$(mktemp)"

    mkdir -p "$(dirname "$attributes_file")"

    if [[ -f "$attributes_file" ]]; then
        while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ "$line" == *"filter=local-override"* ]]; then
                continue
            fi
            if [[ "$line" == *"Auto-generated by git-local-override"* ]]; then
                continue
            fi
            printf '%s\n' "$line" >> "$temp_file"
            ((preserved_line_count++)) || true
        done < "$attributes_file"
    fi

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        [[ -n "$entry" ]] || continue

        target="${entry%%|*}"
        [[ -n "$target" ]] || continue

        if [[ $'\n'"$seen_targets"$'\n' == *$'\n'"$target"$'\n'* ]]; then
            continue
        fi

        seen_targets="$seen_targets
$target"
        has_targets=true
        ((managed_target_count++)) || true
    done <<< "$config_entries"

    if [[ "$has_targets" == true ]]; then
        if [[ -s "$temp_file" ]]; then
            printf '\n' >> "$temp_file"
        fi

        printf '%s\n' '# Auto-generated by git-local-override — do not edit manually' >> "$temp_file"

        while IFS= read -r target || [[ -n "$target" ]]; do
            [[ -n "$target" ]] || continue
            printf '%s filter=local-override\n' "$target" >> "$temp_file"
        done <<< "$seen_targets"
    fi

    # Explicit guard: callers may run inside an `if (subshell)` where errexit
    # is suppressed and a bare mv failure would leave attributes silently stale.
    mv "$temp_file" "$attributes_file" || return 1

    if [[ "$trace_on" == true ]]; then
        local_override_trace_log "sync_attributes path=$attributes_file preserved_lines=$preserved_line_count managed_targets=$managed_target_count total=$(resolver_elapsed_milliseconds "$total_start_ms")ms"
    fi
}

clear_legacy_skip_worktree() {
    local repo_root="$1"
    local config_entries="${2:-}"
    local repaired_count=0
    local seen_targets=""
    local entry=""
    local target=""
    local ls_output=""

    if [[ -z "$config_entries" ]]; then
        config_entries="$(read_config "$repo_root")"
    fi

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        [[ -z "$entry" ]] && continue

        target="${entry%%|*}"
        [[ -n "$target" ]] || continue

        if [[ $'\n'"$seen_targets"$'\n' == *$'\n'"$target"$'\n'* ]]; then
            continue
        fi
        seen_targets="$seen_targets
$target"

        if ! git -C "$repo_root" ls-files --error-unmatch -- "$target" >/dev/null 2>&1; then
            continue
        fi

        ls_output="$(git -C "$repo_root" ls-files -v -- "$target" 2>/dev/null || true)"
        if [[ "${ls_output:0:1}" != "S" ]]; then
            continue
        fi

        git -C "$repo_root" update-index --no-skip-worktree -- "$target"
        ((repaired_count++)) || true
    done <<< "$config_entries"

    printf '%s\n' "$repaired_count"
}

# Per-worktree marker recording that the one-time legacy skip-worktree repair has
# already run. skip-worktree is per-worktree index state, so the marker is keyed
# to the per-worktree absolute git dir (like get_post_commit_state_file), not the
# shared common dir — each worktree migrates its own index once.
skip_worktree_repair_marker() {
    local repo_root="$1"
    local worktree_git_dir=""

    worktree_git_dir="$(git -C "$repo_root" rev-parse --absolute-git-dir 2>/dev/null || echo "")"
    [[ -n "$worktree_git_dir" ]] || return 1

    printf '%s\n' "$worktree_git_dir/local-override-skipworktree-repaired"
}

# One-shot gated form of clear_legacy_skip_worktree for the hot paths
# (post-checkout, pre-commit, pre-rebase). Once the per-worktree marker exists the
# repair is skipped, so the two git subprocesses per managed target are only paid
# once per worktree instead of on every checkout/commit. install/sync-filters call
# the ungated clear_legacy_skip_worktree directly and remain the escape hatch for
# stray legacy bits. Prints the repaired count (0 when short-circuited) to match
# the count contract callers expect.
clear_legacy_skip_worktree_once() {
    local repo_root="$1"
    local config_entries="${2:-}"
    local marker=""
    local repaired=""

    marker="$(skip_worktree_repair_marker "$repo_root" 2>/dev/null || true)"
    if [[ -n "$marker" && -f "$marker" ]]; then
        printf '0\n'
        return 0
    fi

    repaired="$(clear_legacy_skip_worktree "$repo_root" "$config_entries")"
    [[ -n "$marker" ]] && : > "$marker"
    printf '%s\n' "$repaired"
}

cache_config_files() {
    local repo_root="$1"
    # Already cached for this root; callers that mutate config files must
    # clear_config_files_cache first.
    if [[ -n "$_DISCOVER_CACHE_FILE" && -f "$_DISCOVER_CACHE_FILE" \
        && "$_DISCOVER_CACHE_ROOT" == "$repo_root" ]]; then
        return 0
    fi
    clear_config_files_cache
    _DISCOVER_CACHE_FILE="$(mktemp)"
    _DISCOVER_CACHE_ROOT="$repo_root"
    discover_config_files "$repo_root" > "$_DISCOVER_CACHE_FILE"
}

clear_config_files_cache() {
    if [[ -n "$_DISCOVER_CACHE_FILE" && -f "$_DISCOVER_CACHE_FILE" ]]; then
        rm -f "$_DISCOVER_CACHE_FILE"
    fi
    _DISCOVER_CACHE_FILE=""
    _DISCOVER_CACHE_ROOT=""
}

get_cached_config_files() {
    local repo_root="$1"
    if [[ -n "$_DISCOVER_CACHE_FILE" && -f "$_DISCOVER_CACHE_FILE" \
        && "$_DISCOVER_CACHE_ROOT" == "$repo_root" ]]; then
        local_override_trace_log "discover_config_files cache=hit file=$_DISCOVER_CACHE_FILE"
        cat "$_DISCOVER_CACHE_FILE"
    else
        local_override_trace_log "discover_config_files cache=miss"
        discover_config_files "$repo_root"
    fi
}

trim_config_value() {
    local value="$1"

    value="${value#\"}"
    value="${value%\"}"
    value="${value#\'}"
    value="${value%\'}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"

    printf '%s\n' "$value"
}

config_dir_for_path() {
    local config_path="$1"

    if [[ "$config_path" == */* ]]; then
        printf '%s\n' "${config_path%/*}"
    else
        printf '.\n'
    fi
}

path_is_within_dir() {
    local path="$1"
    local dir="$2"

    if [[ "$dir" == "." ]]; then
        return 0
    fi

    [[ "$path" == "$dir" || "$path" == "$dir/"* ]]
}

dir_is_descendant_of() {
    local parent_dir="$1"
    local child_dir="$2"

    if [[ "$parent_dir" == "." ]]; then
        [[ "$child_dir" != "." ]]
        return
    fi

    [[ "$child_dir" == "$parent_dir/"* ]]
}

normalize_config_path() {
    local base_dir="$1"
    local raw_path="$2"
    local combined_path=""
    local part=""
    local normalized=""
    local last_index=0
    local -a path_parts
    local -a normalized_parts

    [[ -n "$raw_path" ]] || return 1
    [[ "$raw_path" != /* ]] || return 1

    if [[ "$base_dir" == "." || -z "$base_dir" ]]; then
        combined_path="$raw_path"
    else
        combined_path="$base_dir/$raw_path"
    fi

    IFS='/' read -r -a path_parts <<< "$combined_path"
    for part in "${path_parts[@]}"; do
        if [[ -z "$part" || "$part" == "." ]]; then
            continue
        fi

        if [[ "$part" == ".." ]]; then
            if [[ ${#normalized_parts[@]} -eq 0 ]]; then
                return 1
            fi
            last_index=$((${#normalized_parts[@]} - 1))
            unset "normalized_parts[$last_index]"
            continue
        fi

        normalized_parts+=("$part")
    done

    for part in "${normalized_parts[@]}"; do
        if [[ -n "$normalized" ]]; then
            normalized="$normalized/$part"
        else
            normalized="$part"
        fi
    done

    [[ -n "$normalized" ]] || return 1
    printf '%s\n' "$normalized"
}

# Reject a managed path whose on-disk form is a symlink or resolves outside
# the repo root. Lexical validation (normalize_config_path) is not enough:
# cp/redirect follow symlinks, so a committed symlink target lets a hostile
# repo write outside the checkout. $1 = repo root, $2 = repo-relative path.
# Returns 0 when the path is safe to read/write, 1 when it must be refused.
path_is_symlink_safe() {
    local repo_root="$1"
    local rel_path="$2"
    local full_path="$repo_root/$rel_path"
    local resolved=""
    local resolved_root=""

    # Any symlink component on the path is refused outright.
    if [[ -L "$full_path" ]]; then
        return 1
    fi

    # Resolve the parent dir (it may legitimately not exist yet for a new
    # override file) and confirm the final real path stays under the repo root.
    resolved_root="$(cd "$repo_root" 2>/dev/null && pwd -P)" || return 1
    local parent_dir=""
    parent_dir="$(dirname "$full_path")"
    if [[ -d "$parent_dir" ]]; then
        resolved="$(cd "$parent_dir" 2>/dev/null && pwd -P)/$(basename "$full_path")" || return 1
        case "$resolved" in
            "$resolved_root"/*) return 0 ;;
            *) return 1 ;;
        esac
    fi

    return 0
}

# Escape fd glob metacharacters so a literal path can be used as an -E
# exclude pattern. An invalid glob makes fd exit non-zero, which discovery
# swallows into an empty result — every config silently lost.
escape_fd_glob() {
    printf '%s\n' "$1" | sed 's/[][\*?{}]/\\&/g'
}

# Emit `git worktree list --porcelain` records NUL-terminated. `-z` (git >=
# 2.36) is preferred: it is the only form that survives newlines in worktree
# paths. Older gits fall back to converting the newline-terminated porcelain
# output to NUL records — identical parsing, with the pre-existing
# newline-in-path limitation confined to those gits.
list_worktrees_porcelain_nul() {
    local repo_root="$1"

    if git -C "$repo_root" worktree list --porcelain -z 2>/dev/null; then
        return 0
    fi
    git -C "$repo_root" worktree list --porcelain 2>/dev/null | tr '\n' '\0'
}

# Repo-relative directories of linked worktrees that live INSIDE repo_root.
# Another checkout's config is not a subtree config of this checkout.
get_nested_worktree_dirs() {
    local repo_root="$1"
    local canonical_root=""
    local line=""
    local wt_path=""

    # `git worktree list` resolves symlinks in the paths it prints (e.g. macOS
    # /var -> /private/var), so compare against repo_root's resolved form too
    # or every entry silently fails the prefix match.
    canonical_root="$(git -C "$repo_root" rev-parse --show-toplevel 2>/dev/null || echo "$repo_root")"

    while IFS= read -r -d '' line || [[ -n "$line" ]]; do
        case "$line" in
            worktree\ *)
                wt_path="${line#worktree }"
                [[ "$wt_path" == "$canonical_root" ]] && continue
                case "$wt_path" in
                    "$canonical_root"/*)
                        printf '%s\n' "${wt_path#"$canonical_root"/}"
                        ;;
                esac
                ;;
        esac
    done < <(list_worktrees_porcelain_nul "$repo_root")
}

discover_config_files() {
    local repo_root="$1"
    local seen=""
    local path=""
    local discover_output=""
    local strategy="git"
    local trace_on=false
    local discover_start_ms
    local tracked_start_ms
    local tracked_ms=0
    local ignored_start_ms
    local ignored_ms=0
    local tracked_output=""
    local ignored_output=""
    local combined_output=""
    local nested_dirs=""
    local nested_dir=""
    local under_nested=false
    local -a fd_exclude_args
    local nested_exclude_count=0

    nested_dirs="$(get_nested_worktree_dirs "$repo_root")"

    if local_override_trace_enabled; then
        trace_on=true
        discover_start_ms="$(resolver_now_milliseconds)"
        tracked_start_ms="$discover_start_ms"
    fi

    if command -v fd >/dev/null 2>&1; then
        strategy="fd"
        # Prune nested checkouts during traversal: fd otherwise descends into
        # every linked worktree checked out under this root, which dominates
        # the walk in large monorepos. The post-hoc filter below still guards
        # correctness if an exclude glob fails to match.
        fd_exclude_args=()
        if [[ -n "$nested_dirs" ]]; then
            while IFS= read -r nested_dir; do
                [[ -n "$nested_dir" ]] || continue
                fd_exclude_args+=(-E "$(escape_fd_glob "$nested_dir")")
                ((nested_exclude_count++)) || true
            done <<< "$nested_dirs"
        fi
        discover_output="$(fd --hidden --no-ignore ${fd_exclude_args[@]+"${fd_exclude_args[@]}"} --glob "$CONFIG_FILE_NAME" "$repo_root" 2>/dev/null || true)"
        combined_output="$(printf '%s\n' "$discover_output" | LC_ALL=C sort)"
        tracked_output="$combined_output"
        if [[ "$trace_on" == true ]]; then
            tracked_ms="$(resolver_elapsed_milliseconds "$tracked_start_ms")"
        fi
    else
        tracked_output="$(git -C "$repo_root" ls-files --cached --others --exclude-standard --full-name -- "$CONFIG_FILE_NAME" "*/$CONFIG_FILE_NAME" 2>/dev/null || true)"

        if [[ "$trace_on" == true ]]; then
            tracked_ms="$(resolver_elapsed_milliseconds "$tracked_start_ms")"
            ignored_start_ms="$(resolver_now_milliseconds)"
        fi

        ignored_output="$(git -C "$repo_root" ls-files --others --ignored --exclude-standard --full-name -- "$CONFIG_FILE_NAME" "*/$CONFIG_FILE_NAME" 2>/dev/null || true)"
        combined_output="$({ printf '%s\n' "$tracked_output"; printf '%s\n' "$ignored_output"; } | LC_ALL=C sort)"

        if [[ "$trace_on" == true ]]; then
            ignored_ms="$(resolver_elapsed_milliseconds "$ignored_start_ms")"
        fi
    fi

    while IFS= read -r path || [[ -n "$path" ]]; do
        [[ -n "$path" ]] || continue
        path="${path#"$repo_root"/}"
        path="${path#./}"
        [[ "$path" == "$CONFIG_FILE_NAME" || "$path" == */$CONFIG_FILE_NAME ]] || continue
        [[ -f "$repo_root/$path" ]] || continue

        if [[ -n "$nested_dirs" ]]; then
            under_nested=false
            while IFS= read -r nested_dir; do
                [[ -n "$nested_dir" ]] || continue
                case "$path" in
                    "$nested_dir"/*)
                        under_nested=true
                        break
                        ;;
                esac
            done <<< "$nested_dirs"
            if [[ "$under_nested" == true ]]; then
                local_override_trace_log "discover: skipping nested-worktree config $path"
                continue
            fi
        fi

        if [[ $'\n'"$seen"$'\n' == *$'\n'"$path"$'\n'* ]]; then
            continue
        fi

        seen="$seen
$path"
        printf '%s\n' "$path"
    done <<< "$combined_output"

    if [[ "$trace_on" == true ]]; then
        local_override_trace_log "discover_config_files strategy=${strategy} excluded=${nested_exclude_count} tracked_ms=${tracked_ms} ignored_ms=${ignored_ms} total_ms=$(resolver_elapsed_milliseconds "$discover_start_ms") count=$(count_list_entries "$seen")"
    fi
}

has_any_config() {
    local repo_root="$1"
    local config_path=""

    while IFS= read -r config_path || [[ -n "$config_path" ]]; do
        [[ -n "$config_path" ]] || continue
        return 0
    done < <(get_cached_config_files "$repo_root")

    return 1
}

read_pattern_from_config() {
    local repo_root="$1"
    local config_path="$2"
    local config_file="$repo_root/$config_path"
    local line=""

    [[ -f "$config_file" ]] || return 0

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -z "$line" || "$line" == \#* ]] && continue

        if [[ "$line" =~ ^pattern:[[:space:]]*(.+)$ ]]; then
            trim_config_value "${BASH_REMATCH[1]}"
            return 0
        fi
    done < "$config_file"

    return 0
}

read_pattern() {
    local repo_root="$1"
    read_pattern_from_config "$repo_root" "$CONFIG_FILE_NAME"
}

find_nearest_config_for_path() {
    local repo_root="$1"
    local path="$2"
    local current_dir=""
    local candidate=""

    if [[ "$path" == */* ]]; then
        current_dir="${path%/*}"
    else
        current_dir="."
    fi

    while true; do
        if [[ "$current_dir" == "." ]]; then
            candidate="$CONFIG_FILE_NAME"
        else
            candidate="$current_dir/$CONFIG_FILE_NAME"
        fi

        if [[ -f "$repo_root/$candidate" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi

        if [[ "$current_dir" == "." ]]; then
            break
        fi

        if [[ "$current_dir" == */* ]]; then
            current_dir="${current_dir%/*}"
        else
            current_dir="."
        fi
    done

    return 1
}

get_effective_pattern_for_config() {
    local repo_root="$1"
    local config_path="$2"
    local current_config="$config_path"
    local current_dir=""
    local pattern=""

    while true; do
        pattern="$(read_pattern_from_config "$repo_root" "$current_config")"
        if [[ -n "$pattern" ]]; then
            printf '%s\n' "$pattern"
            return 0
        fi

        current_dir="$(config_dir_for_path "$current_config")"
        if [[ "$current_dir" == "." ]]; then
            break
        fi

        if [[ "$current_dir" == */* ]]; then
            current_dir="${current_dir%/*}"
            current_config="$current_dir/$CONFIG_FILE_NAME"
        else
            current_config="$CONFIG_FILE_NAME"
        fi
    done

    return 0
}

read_config_entries_for_file() {
    local repo_root="$1"
    local config_path="$2"
    local config_file="$repo_root/$config_path"
    local config_dir=""
    local current_override=""
    local in_files_section=false
    local in_replaces_section=false
    local line=""
    local target=""

    [[ -f "$config_file" ]] || return 0

    config_dir="$(config_dir_for_path "$config_path")"

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -z "$line" || "$line" == \#* ]] && continue

        if [[ "$line" =~ ^files:[[:space:]]*$ ]]; then
            in_files_section=true
            in_replaces_section=false
            continue
        fi

        if [[ "$line" =~ ^pattern: ]]; then
            continue
        fi

        if [[ "$line" =~ ^[a-z_]+:[[:space:]]*$ && ! "$line" =~ ^[[:space:]] ]]; then
            in_files_section=false
            in_replaces_section=false
            continue
        fi

        [[ "$in_files_section" == true ]] || continue

        if [[ "$line" =~ ^[[:space:]]*-[[:space:]]+override:[[:space:]]+(.+)$ ]]; then
            current_override="$(trim_config_value "${BASH_REMATCH[1]}")"
            if ! current_override="$(normalize_config_path "$config_dir" "$current_override")"; then
                echo "Error: Override path in '$config_path' is invalid or escapes its subtree" >&2
                printf '%s|%s\n' "$LOCAL_OVERRIDE_PARSE_ERROR_SENTINEL" "$config_path"
                return 1
            fi
            in_replaces_section=false
            continue
        fi

        if [[ -n "$current_override" && "$line" =~ ^[[:space:]]+replaces:[[:space:]]*$ ]]; then
            in_replaces_section=true
            continue
        fi

        if [[ "$in_replaces_section" == true && "$line" =~ ^[[:space:]]+-[[:space:]]+(.+)$ ]]; then
            target="$(trim_config_value "${BASH_REMATCH[1]}")"
            if ! target="$(normalize_config_path "$config_dir" "$target")"; then
                echo "Error: Target path in '$config_path' is invalid or escapes its subtree" >&2
                printf '%s|%s\n' "$LOCAL_OVERRIDE_PARSE_ERROR_SENTINEL" "$config_path"
                return 1
            fi
            [[ -n "$target" ]] && printf '%s|%s\n' "$target" "$current_override"
            continue
        fi

        if [[ "$line" =~ ^[[:space:]]*-[[:space:]] ]]; then
            in_replaces_section=false
            current_override=""
        fi
    done < "$config_file"
}

target_is_shadowed_by_child_config() {
    local repo_root="$1"
    local config_path="$2"
    local target="$3"
    local config_dir=""
    local child_config=""
    local child_dir=""

    config_dir="$(config_dir_for_path "$config_path")"

    while IFS= read -r child_config || [[ -n "$child_config" ]]; do
        [[ -n "$child_config" ]] || continue
        [[ "$child_config" != "$config_path" ]] || continue

        child_dir="$(config_dir_for_path "$child_config")"
        if dir_is_descendant_of "$config_dir" "$child_dir" && path_is_within_dir "$target" "$child_dir"; then
            return 0
        fi
    done < <(get_cached_config_files "$repo_root")

    return 1
}

validate_config() {
    local repo_root="$1"
    local seen_targets=""
    local config_path=""
    local config_dir=""
    local pattern=""
    local entry=""
    local target=""
    local override=""
    local validate_start_ms
    local config_start_ms
    local config_entry_count=0

    validate_start_ms="$(resolver_now_milliseconds)"

    if ! has_any_config "$repo_root"; then
        return 0
    fi

    while IFS= read -r config_path || [[ -n "$config_path" ]]; do
        [[ -n "$config_path" ]] || continue
        config_start_ms="$(resolver_now_milliseconds)"
        config_entry_count=0

        pattern="$(get_effective_pattern_for_config "$repo_root" "$config_path")"
        if [[ -z "$pattern" ]]; then
            echo "Error: Missing required 'pattern:' field for '$config_path'" >&2
            echo "  Add a pattern field there or in an ancestor $CONFIG_FILE_NAME:" >&2
            echo "    pattern: \".local\"" >&2
            return 1
        fi

        config_dir="$(config_dir_for_path "$config_path")"

        while IFS= read -r entry || [[ -n "$entry" ]]; do
            [[ -n "$entry" ]] || continue
            ((config_entry_count++)) || true
            target="${entry%%|*}"
            override="${entry#*|}"

            if [[ "$target" == "$LOCAL_OVERRIDE_PARSE_ERROR_SENTINEL" ]]; then
                echo "Error: '$override' contains an invalid path entry" >&2
                return 1
            fi

            if ! path_is_within_dir "$target" "$config_dir"; then
                echo "Error: Target '$target' in '$config_path' escapes its subtree" >&2
                return 1
            fi

            if ! path_is_within_dir "$override" "$config_dir"; then
                echo "Error: Override '$override' in '$config_path' escapes its subtree" >&2
                return 1
            fi

            if [[ "$target" == "$override" ]]; then
                echo "Error: Target '$target' in '$config_path' cannot replace itself" >&2
                return 1
            fi

            if [[ "$target" == "$CONFIG_FILE_NAME" || "$target" == */$CONFIG_FILE_NAME ]]; then
                echo "Error: '$config_path' cannot manage another $CONFIG_FILE_NAME file ('$target')" >&2
                return 1
            fi

            if target_is_shadowed_by_child_config "$repo_root" "$config_path" "$target"; then
                echo "Error: Target '$target' in '$config_path' belongs to a child subtree config" >&2
                return 1
            fi

            if [[ $'\n'"$seen_targets"$'\n' == *$'\n'"$target"$'\n'* ]]; then
                echo "Error: Duplicate target file '$target' across recursive configs" >&2
                echo "  Each file can only appear in one effective 'replaces:' list" >&2
                return 1
            fi

            seen_targets="$seen_targets
$target"
        done < <(read_config_entries_for_file "$repo_root" "$config_path")

        local_override_trace_log "validate_config config=$config_path pattern=$pattern entries=$config_entry_count ms=$(resolver_elapsed_milliseconds "$config_start_ms")"
    done < <(get_cached_config_files "$repo_root")

    local_override_trace_log "validate_config total_ms=$(resolver_elapsed_milliseconds "$validate_start_ms") unique_targets=$(count_list_entries "$seen_targets")"

    return 0
}

read_config() {
    local repo_root="$1"
    local seen_targets=""
    local config_path=""
    local entry=""
    local target=""
    local read_start_ms
    local emitted_count=0
    local duplicate_skip_count=0
    local shadowed_skip_count=0

    read_start_ms="$(resolver_now_milliseconds)"

    while IFS= read -r config_path || [[ -n "$config_path" ]]; do
        [[ -n "$config_path" ]] || continue

        while IFS= read -r entry || [[ -n "$entry" ]]; do
            [[ -n "$entry" ]] || continue
            target="${entry%%|*}"

            # Parse-error sentinel: the authoritative rejection happens in
            # validate_config; this hot path just skips the marker.
            if [[ "$target" == "$LOCAL_OVERRIDE_PARSE_ERROR_SENTINEL" ]]; then
                continue
            fi

            if target_is_shadowed_by_child_config "$repo_root" "$config_path" "$target"; then
                ((shadowed_skip_count++)) || true
                continue
            fi

            if [[ $'\n'"$seen_targets"$'\n' == *$'\n'"$target"$'\n'* ]]; then
                ((duplicate_skip_count++)) || true
                continue
            fi

            seen_targets="$seen_targets
$target"
            ((emitted_count++)) || true
            printf '%s\n' "$entry"
        done < <(read_config_entries_for_file "$repo_root" "$config_path")
    done < <(get_cached_config_files "$repo_root")

    local_override_trace_log "read_config emitted=$emitted_count shadowed_skips=$shadowed_skip_count duplicate_skips=$duplicate_skip_count total_ms=$(resolver_elapsed_milliseconds "$read_start_ms")"
}

get_override_for_target() {
    local target_path="$1"
    local repo_root="$2"
    local owner_config=""
    local entry=""
    local target=""
    local override=""

    owner_config="$(find_nearest_config_for_path "$repo_root" "$target_path" 2>/dev/null || true)"
    [[ -n "$owner_config" ]] || return 1

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        [[ -z "$entry" ]] && continue
        target="${entry%%|*}"
        # Skip the parse-error sentinel; validate_config is the gate for it.
        if [[ "$target" == "$LOCAL_OVERRIDE_PARSE_ERROR_SENTINEL" ]]; then
            continue
        fi
        override="${entry#*|}"
        if [[ "$target" == "$target_path" ]]; then
            printf '%s\n' "$override"
            return 0
        fi
    done < <(read_config_entries_for_file "$repo_root" "$owner_config")

    return 1
}

get_config_for_target() {
    local target_path="$1"
    local repo_root="$2"
    local config_path=""
    local entry=""
    local target=""

    while IFS= read -r config_path || [[ -n "$config_path" ]]; do
        [[ -n "$config_path" ]] || continue

        while IFS= read -r entry || [[ -n "$entry" ]]; do
            [[ -n "$entry" ]] || continue
            target="${entry%%|*}"
            # Skip the parse-error sentinel; validate_config is the gate for it.
            if [[ "$target" == "$LOCAL_OVERRIDE_PARSE_ERROR_SENTINEL" ]]; then
                continue
            fi
            if [[ "$target" == "$target_path" ]]; then
                printf '%s\n' "$config_path"
                return 0
            fi
        done < <(read_config_entries_for_file "$repo_root" "$config_path")
    done < <(get_cached_config_files "$repo_root")

    return 1
}

get_override_files() {
    local repo_root="$1"
    local seen=""
    local entry=""
    local override=""

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        [[ -z "$entry" ]] && continue
        override="${entry#*|}"
        [[ -z "$override" ]] && continue

        if ! [[ $'\n'"$seen"$'\n' == *$'\n'"$override"$'\n'* ]]; then
            printf '%s\n' "$override"
            seen="$seen
$override"
        fi
    done < <(read_config "$repo_root")
}

get_targets_for_override() {
    local repo_root="$1"
    local override_file="$2"
    local entry=""
    local target=""
    local override=""

    while IFS= read -r entry || [[ -n "$entry" ]]; do
        [[ -z "$entry" ]] && continue
        target="${entry%%|*}"
        override="${entry#*|}"

        if [[ "$override" == "$override_file" ]]; then
            printf '%s\n' "$target"
        fi
    done < <(read_config "$repo_root")
}

worktree_fallback_disabled() {
    [[ "${GIT_LOCAL_OVERRIDE_DISABLE_WORKTREE_FALLBACK:-0}" == "1" ]]
}

is_linked_worktree() {
    local repo_root="$1"
    local git_dir=""
    local common_dir=""

    git_dir="$(git -C "$repo_root" rev-parse --git-dir 2>/dev/null || echo "")"
    common_dir="$(git -C "$repo_root" rev-parse --git-common-dir 2>/dev/null || echo "")"
    [[ -n "$git_dir" && -n "$common_dir" ]] || return 1

    [[ "$git_dir" != "$common_dir" ]]
}

# First "worktree " entry of `git worktree list --porcelain` is the main
# worktree — unless its block carries the `bare` attribute, in which case
# there is no main checkout to resolve against and we return 1.
get_main_worktree_root() {
    local repo_root="$1"
    local line=""
    local first_root=""

    while IFS= read -r -d '' line || [[ -n "$line" ]]; do
        if [[ -z "$first_root" ]]; then
            case "$line" in
                worktree\ *) first_root="${line#worktree }" ;;
            esac
            continue
        fi
        case "$line" in
            bare) return 1 ;;
            "" | worktree\ *) break ;;
        esac
    done < <(list_worktrees_porcelain_nul "$repo_root")

    [[ -n "$first_root" ]] || return 1
    printf '%s\n' "$first_root"
}

# The root that configs and override files are resolved against. Normally the
# checkout root itself; for a linked worktree with no config of its own, the
# main worktree root (a worktree-local config always wins, all-or-nothing).
get_resolution_root() {
    local repo_root="$1"
    local main_root=""

    if worktree_fallback_disabled; then
        printf '%s\n' "$repo_root"
        return 0
    fi

    if ! is_linked_worktree "$repo_root"; then
        printf '%s\n' "$repo_root"
        return 0
    fi

    if has_any_config "$repo_root"; then
        printf '%s\n' "$repo_root"
        return 0
    fi

    main_root="$(get_main_worktree_root "$repo_root" 2>/dev/null || echo "")"
    if [[ -z "$main_root" || ! -d "$main_root" ]]; then
        local_override_trace_log "get_resolution_root: no main worktree root; fallback skipped"
        printf '%s\n' "$repo_root"
        return 0
    fi

    local_override_trace_log "get_resolution_root: falling back to main worktree root $main_root"
    printf '%s\n' "$main_root"
}

# Returns the ABSOLUTE path of the override file for a managed target, or
# nothing. Resolves against the checkout's resolution root, so linked
# worktrees without their own config inherit the main worktree's overrides.
get_override_for_file() {
    local repo_root="$1"
    local file_path="$2"
    local resolution_root=""
    local override=""

    resolution_root="$(get_resolution_root "$repo_root")"
    override="$(get_override_for_target "$file_path" "$resolution_root" 2>/dev/null || true)"
    [[ -n "$override" ]] || return 0

    printf '%s/%s\n' "$resolution_root" "$override"
}

is_rebase_in_progress() {
    local repo_root="$1"
    local rebase_merge_path=""
    local rebase_apply_path=""

    rebase_merge_path="$(git -C "$repo_root" rev-parse --git-path rebase-merge 2>/dev/null || true)"
    rebase_apply_path="$(git -C "$repo_root" rev-parse --git-path rebase-apply 2>/dev/null || true)"

    if [[ "${GIT_REFLOG_ACTION:-}" == rebase* ]]; then
        return 0
    fi

    if [[ -n "$rebase_merge_path" && -d "$rebase_merge_path" ]]; then
        return 0
    fi

    if [[ -n "$rebase_apply_path" && -d "$rebase_apply_path" ]]; then
        return 0
    fi

    return 1
}

# ---------------------------------------------------------------------------
# Smudge/clean filter cores.
#
# These are the single, canonical implementation of the git smudge/clean
# filters. They are shared by BOTH entry points:
#   - the git-invoked hook scripts hooks/local-override-filter-{smudge,clean}
#   - the CLI subcommands `git-local-override filter-{smudge,clean}`
# Git actually runs the hooks, so the hook behavior is authoritative; routing
# the CLI subcommands through the same core keeps them byte-identical on stdout
# and prevents the two from silently drifting.
#
# INTENTIONAL ASYMMETRY (do not "fix"): the smudge core carries an
# is_rebase_in_progress passthrough guard; the clean core deliberately has NO
# rebase guard. During a rebase git checks out tracked blobs as part of its
# internal machinery, and emitting the override there interferes with the
# rebase (commit 75d4df6, "fix(rebase): prevent override interference during
# rebase internals"). The clean path has no such hazard, so it keeps
# transforming even mid-rebase. Keep this difference.
#
# BYTE-EXACTNESS: never capture filter output via $(...) — command
# substitution strips trailing newlines and cannot carry NUL bytes, which
# would break the clean(smudge(original)) == original roundtrip invariant. The
# clean core captures stdin and `git show` output into temp files instead.
# ---------------------------------------------------------------------------

# Reads original blob content on stdin, writes smudged content to stdout.
# $1 = file path (%f). Emits the local override content when a safe override
# exists, otherwise passes the incoming blob through unchanged.
run_local_override_smudge() {
    local file_path="${1:-}"

    if [[ "${GIT_LOCAL_OVERRIDE_DISABLE:-0}" == "1" ]]; then
        cat
        return 0
    fi

    local repo_root
    repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
        cat
        return 0
    }
    if [[ -z "$repo_root" ]]; then
        cat
        return 0
    fi

    # During rebase, always passthrough tracked blob content (see 75d4df6).
    if is_rebase_in_progress "$repo_root"; then
        cat
        return 0
    fi

    local override_file
    override_file="$(get_override_for_file "$repo_root" "$file_path")"

    # A symlinked override would leak outside-repo content into the tree; fall
    # through to plain passthrough instead of emitting the link target.
    if [[ -n "$override_file" && -f "$override_file" ]] \
       && path_is_symlink_safe "$(dirname "$override_file")" "$(basename "$override_file")"; then
        cat > /dev/null
        cat "$override_file"
        return 0
    fi

    cat
}

# Reads working-tree content on stdin, writes cleaned content to stdout.
# $1 = file path (%f). When the incoming content is exactly the local override,
# substitutes the original tracked content from the git index so git sees the
# file as unmodified; otherwise passes the input through unchanged.
#
# NOTE: no is_rebase_in_progress guard here — this is deliberate; see the
# "INTENTIONAL ASYMMETRY" note above (commit 75d4df6).
run_local_override_clean() {
    local file_path="${1:-}"
    local stdin_tmp=""
    local override_file=""
    local compare_matched="no"
    local trace_on=false
    local total_start_ms=0
    local phase_start_ms=0
    local resolve_override_ms=0
    local git_show_ms=0

    if local_override_trace_enabled; then
        trace_on=true
        total_start_ms="$(resolver_now_milliseconds)"
    fi

    stdin_tmp="$(mktemp "${TMPDIR:-/tmp}/local-override-clean.XXXXXX")"
    cat > "$stdin_tmp"

    if [[ "${GIT_LOCAL_OVERRIDE_DISABLE:-0}" == "1" ]]; then
        cat "$stdin_tmp"
        rm -f "$stdin_tmp"
        return 0
    fi

    local repo_root
    repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
        cat "$stdin_tmp"
        rm -f "$stdin_tmp"
        return 0
    }
    if [[ -z "$repo_root" ]]; then
        cat "$stdin_tmp"
        rm -f "$stdin_tmp"
        return 0
    fi

    override_file="$(get_override_for_file "$repo_root" "$file_path")"
    if [[ "$trace_on" == true ]]; then
        resolve_override_ms="$(resolver_elapsed_milliseconds "$total_start_ms")"
    fi

    if [[ -n "$override_file" && -f "$override_file" ]] \
       && path_is_symlink_safe "$(dirname "$override_file")" "$(basename "$override_file")"; then
        # Only transform when incoming content is exactly the local override.
        # If caller already provided original/tracked content (e.g., pre-commit
        # restored file), passthrough avoids clobbering intended staged content.
        if cmp -s "$stdin_tmp" "$override_file"; then
            compare_matched="yes"
            if [[ "$trace_on" == true ]]; then
                phase_start_ms="$(resolver_now_milliseconds)"
            fi
            # Single `git show` captured to a temp file (not `$(...)`, which
            # strips trailing newlines and would break byte-exact roundtrip).
            local index_tmp
            index_tmp="$(mktemp "${TMPDIR:-/tmp}/local-override-index.XXXXXX")"
            if git -C "$repo_root" show ":$file_path" > "$index_tmp" 2>/dev/null; then
                cat "$index_tmp"
                if [[ "$trace_on" == true ]]; then
                    git_show_ms="$(resolver_elapsed_milliseconds "$phase_start_ms")"
                    local_override_trace_log "clean" "file=$file_path override=$override_file matched=$compare_matched transformed=1 resolve_override=${resolve_override_ms}ms git_show=${git_show_ms}ms total=$(resolver_elapsed_milliseconds "$total_start_ms")ms"
                fi
                rm -f "$index_tmp" "$stdin_tmp"
                return 0
            fi
            rm -f "$index_tmp"
        fi
    fi

    if [[ "$trace_on" == true ]]; then
        local_override_trace_log "clean" "file=$file_path override=${override_file:-none} matched=$compare_matched transformed=0 resolve_override=${resolve_override_ms}ms total=$(resolver_elapsed_milliseconds "$total_start_ms")ms"
    fi

    cat "$stdin_tmp"
    rm -f "$stdin_tmp"
}
